spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/claims_db
    username: postgres
    password: "@Vanshika06"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

